language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - sudo apt-get install python-tk
  - sudo apt-get install python-imaging-tk

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - flake8 .
